<?php

$title = 'Add new article';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php print $this->showMessages();?>
<?php
$form = $this->form;
$form->setAttribute('accept-charset', 'utf-8');
$form->setAttribute('action', $this->url('blog', array('action' => 'add')));
$form->prepare();


echo $this->form()->openTag($form);
foreach ($form as $element) :
?>
<div class="control-group <?php if($this->formElementErrors($element)) 
                                echo "error" ?>">
    <label class="control-label"><?php echo $element->getLabel() ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>

<?php
endforeach;

echo $this->form()->closeTag($form);
?>
