<?php
 
$title = 'Delete article';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
 
<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($article->getTitle()); ?>' by
    '<?php echo $this->escapeHtml($article->getAuthor()); ?>'?
</p>
 <?php echo $this->showMessages();?>
<?php
$url = $this->url('blog', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $article->getId(); ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>